### ISSUE TITLE
As a user, user can see others' name when click/tap each marker.

### ISSUE THREAD

**Issue by duyoji** [duyoji/oni-on-cheese#76]
## Example image

In #72, I implemented [`InfoWindow`](https://tomchentw.github.io/react-google-maps/#infowindow) above marker that is shown when users click/tap the marker.

![image](https://user-images.githubusercontent.com/1068671/34330365-d714b51e-e95e-11e7-8318-fdd1d9bb23b8.png)

### Basic feature

- Now, this application uses `socket.id` as a user id and name.
- Instead of using `socket.id` as a name, User can set own name.
  - [ ] Before starting game, user input his/her name in textbox.
  - [ ] After submit user name, this app stores the name in state of redux.

### Advanced feature

- Store name into localStorage. So user don't need to input his/her name again.
  - [ ] Store user name into localStorage.
  - [ ] If user name is already stored in localStorage, the name is set in textbox in default.

**Comment by duyoji** [comment]
Done by https://github.com/duyoji/oni-on-cheese/pull/78.

**Comment by duyoji** [comment]
In #78, just implemented basic feature.

I will start Advanced feature.

**Comment by duyoji** [comment]
Done Advanced feature by #82.
